### ISSUE TITLE
Doesn't seem to work anymore.

### ISSUE THREAD

**Issue by boolerman123** [Runemker/OPRS-plugin-port-to-Runelite--#2]
I can't seem to get this to work.

If this is broken please update it :)

If this is still working please elaborate on the installation :)

**Comment by Runemker** [comment]
Fixed it. Enjoy it till the next time.

**Comment by boolerman123** [comment]
Hello!  I have re-compiled it and launched the .jar created, however, only a cached version of runelite comes up.  Perhaps I'm missing something as I'm fairly new to IntelliJ.  Could you please elaborate a bit more on the instructions so I can properly use this software?

Thank you!

**Comment by Runemker** [comment]
Open this project in IntelliJ. Look at right taskbar where it say's "Gradle" with a Elephant icon. Go into `Cheating - Task - build`. Right click the "build" and run. Then click on the README.md(should be open by default) and click the green play button to make it build again. Now there should be file called "build". Go into `build - libs` and then right click the "Cheating-1.0-all.jar" file. Go into option "More Run/Debug" and click "Modify Run Configuration". Add "`-ea`" into VM options and click apply at button right then Ok. Now right click "Cheating-1.0-all.jar" and it should run. You'll need to have official runelite downloaded.

If Runelite ever updates just go into the "build.gradle" file and change the version number in `def runeLiteVersion = " "` to the latest version which can be found on their [website](https://runelite.net/) and rebuild it with instructions from above.

**Comment by boolerman123** [comment]
Hmm, I followed these instructions perfectly and I seem to still have the same issue.  Is there a discord/etc I can reach you at to troubleshoot?

**Comment by Runemker** [comment]
It's in the readme, but if you haven't already use Temurin 11. Go to `File - Project Structure - SDKs` Click the `+` and click `Download JDK`. Version: `11`, Vendor: `Eclipse Termurin (AdoptOpenJDK Hotspot)`. Download it then click Apply and OK. Check if the SDK is used by going into `File - Project Structure - Project` and SDK should be "temurin-11"

Try deleting the project and redoing it. Try opening official runelite then close it. This is all I can do if yours doesn't work.
